### ISSUE TITLE
Mouse side buttons not working (XBUTTON1 and XBUTTON2)

### ISSUE THREAD

**Issue by wolimst** [keke1008/hookmap#2]
Hi. Thank you for implementing the library. I'm using it for my personal hotkeys, and this library is showing better response and has more functionality than some of the other libraries that I've tried.

I found some issues while using it. I can submit a PR if that's ok with you, please let me know.

### Summary

Mouse side buttons XBUTTON1 and XBUTTON2 are ignored.
For example, clicking XBUTTON1 is silently ignored in below code, instead of sending the A key.
```rust
let mut hotkey = Hotkey::new();
hotkey.register(Context::new()).remap(Button::SideButton1, Button::A);
hotkey.install();
```

### Cause of the issue

At line 212-213 below, `mouseData: MOUSEHOOKSTRUCTEX_MOUSE_DATA` which holds information about the pressed mouse button is compared to `XBUTTON1: MOUSEHOOKSTRUCTEX_MOUSE_DATA = 1` and `XBUTTON2: MOUSEHOOKSTRUCTEX_MOUSE_DATA = 2` which are constants defined in the `windows-rs` library.

https://github.com/keke1008/hookmap/blob/70a58cc01f6c522160fa3fa2b4a06b1fc5e10b88/hookmap-core/src/sys/windows/hook.rs#L205-L217

Actually, however, `mouseData` holds different values than those constants, `mouseData == 0x1_0000` for XBUTTON1 and `0x2_0000` for XBUTTON2, therefore, the comparisons fail and the button clicks are ignored.

This is caused by a bug from `win32metadata` which `windows-rs` refers to generate the rust code.
Please refer to https://github.com/microsoft/win32metadata/issues/1385 for more detailed information about the bug.

### Possible solution

- Perform `mouseData` comparison after shifting the bits.
- (Optional) Wait until `windows-rs` to release next version which will use the latest `win32metadata` release that fixed above issue, and bump up `windows-rs` dependency version. The constants `XBUTTON1` and `XBUTTON2` will have `u16` type ([pushed in master but not released yet](https://github.com/microsoft/windows-rs/pull/2198/commits/e8368bb2d10c1aec1fce45f153f59bf10507ef43#diff-cfd76474134353e7d3ceb474db4c600cdb3c5b1627330b00d4a2f62ba58ed616R6629-R6632)), therefore direct comparison between `MOUSEHOOKSTRUCTEX_MOUSE_DATA(u32)` and `u16` will cause an error, fix that.

**Comment by keke1008** [comment]
> I found some issues while using it. I can submit a PR if that's ok with you, please let me know.

Thanks! Yes, please do!

> ### Possible solution
> 
>     * Perform `mouseData` comparison after shifting the bits.
> 
>     * (Optional) Wait until `windows-rs` to release next version which will use the latest `win32metadata` release that fixed above issue, and bump up `windows-rs` dependency version. The constants `XBUTTON1` and `XBUTTON2` will have `u16` type ([pushed in master but not released yet](https://github.com/microsoft/windows-rs/pull/2198/commits/e8368bb2d10c1aec1fce45f153f59bf10507ef43#diff-cfd76474134353e7d3ceb474db4c600cdb3c5b1627330b00d4a2f62ba58ed616R6629-R6632)), therefore direct comparison between `MOUSEHOOKSTRUCTEX_MOUSE_DATA(u32)` and `u16` will cause an error, fix that.

I prefer the first one.
But I will revert it when the new `windows-rs` is released.
