### ISSUE TITLE
Support widely used multimedia keys

### ISSUE THREAD

**Issue by wolimst** [keke1008/hookmap#3]
Support some widely used multimedia keys,
such as Volume Up/Down, Mute, Play/Pause/Stop, Next/Previous Track, etc.

References for the virtual keys of some multimedia keys supported by the windows API ([link](https://github.com/microsoft/windows-rs/blob/master/crates/libs/windows/src/Windows/Win32/UI/Input/KeyboardAndMouse/mod.rs#L1377-L1398))

As same as the previous issue that I posted, I can submit a PR if that's ok with you.

**Comment by keke1008** [comment]
Thank you for your suggestion.

I would like to make this library Linux-compatible in the future.
So, if that multimedia key exists in the Linux key code, it is no problem to add it. (Most keys should be fine).

[List of Linux key codes](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h#L75:L339)

I would appreciate it if you create a PR for us.
